# Site settings
title: M KUZNETSOV
email: 
description: > # this means to ignore newlines until "baseurl:"
  THE DIGITAL EXPERIENCE
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mariakuz.github.io" # the base hostname & protocol for your site
twitter_username: m_keigh
github_username: mariakuz

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

#redcarpet:
 # extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
